# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on:
  schedule:
  - cron: "0 22 * * 1" # run Mondays at 22 o'clock
  workflow_dispatch:


name: plot-download-history

jobs:
  plot-downloads-history:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true

      - name: Install packages
        run: install.packages(c("ggplot2", "cranlogs"))
        shell: Rscript {0}

      - name: Draw history
        run: |
          library(ggplot2)
          library(cranlogs)

          df <- cran_downloads("adaptr", from = "2022-03-14", to = Sys.Date() - 1) # today's stats won't be available
          ggplot(df, aes(date, count)) +
            geom_line(size = 0.5) +
            geom_point() +
            theme_minimal() +
            theme(axis.title = element_blank()) +
            labs(title = "Downloads per day since release",
                 subtitle = paste("Total downloads:", scales::comma(sum(df$count)))) # ggplot2 brings scales along

          ggsave(".github/workflows/downloads-history.pdf", units = "cm",
                 width = 15, height = 10)
        shell: Rscript {0}

      - name: Archive plot as artefact
        uses: actions/upload-artifact@v3
        with:
          name: plot-downloads-per-day
          path: .github/workflows/downloads-history.pdf
