# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on:
  schedule:
  - cron: "0 22 * * 1" # run Mondays at 22 o'clock
  workflow_dispatch:


name: plot-download-history

jobs:
  plot-downloads-history:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Draw history
        run: |
          install.packages("cranlogs")

          df <- cranlogs::cran_downloads("adaptr", from = "2022-03-14", to = Sys.Date() - 1)
            # today's stats won't be available

          pdf(file = ".github/workflows/downloads-history.pdf", width = 20/2.54, height = 12/2.54)
            # convert to inches
          plot(df$date, df$count,
               xlab = "Dashed line: mean per day",
               ylab = "No. downloads", type = "l", lwd = 0.5,
               main = paste("Downloads per day since release\n",
                            "Total downloads:",
                            format(sum(df$count), big.mark = ",", scientific = FALSE)))
          abline(a = mean(df[-1, "count"]), b = 0, lty = 2, col = "dodgerblue")
          dev.off()
        shell: Rscript {0}

      - name: Archive plot as artefact
        uses: actions/upload-artifact@v3
        with:
          name: plot-downloads-per-day
          path: .github/workflows/downloads-history.pdf
